### ISSUE TITLE
您好，能否在出一套联想B360 i5-8400核显输出的EFI ？

### ISSUE THREAD

**Issue by mcyaas** [ThrRip/OpenCore-EFI-Lenovo-B360-i5-8400#1]
您好，能否在出一套联想B360 i5-8400核显输出的EFI？
同联想台式机，使用的集成显卡，HDMI输出。目前使用10.15.3，如果>10.15.5显示器会没有信号。
谢谢~

**Comment by ThrRip** [comment]
感谢您对本项目的关注。
很荣幸能为您定制 EFI 文件。
您需要的「联想B360 i5-8400核显输出的EFI」将于近期发布到 GitHub。
为了我能更好地更新、修复您的机型对应的 EFI 文件，希望您能发送电子邮件到 [thrrip@thrrip.space](mailto:thrrip@thrrip.space) 和我取得联系，以便帮助您进行远程调试。
感谢您的支持！

**Comment by mcyaas** [comment]
> 感谢您对本项目的关注。
> 很荣幸能为您定制EFI文件。
> 您需要的「联想B360 i5-8400核显输出的EFI」将于近期发布到GitHub的。
> 为了我能更好地更新，修复您的机类型对应的EFI文件，希望您能发送电子邮件到[thrrip@thrrip.space](mailto:thrrip@thrrip.space)和我取得联系，[刹车帮助](mailto:thrrip@thrrip.space)您进行远程调试。
> 感谢您的支持！

已发邮件，请查收！

**Comment by mcyaas** [comment]
已经解决，谢谢楼主提供的帮助。

https://github.com/mcyaas/ThinkCentre-E96-hackintosh
