### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by AIOFrame** [ThrRip/OpenCore-EFI-Lenovo-B360-i5-8400#2]
Hi I have a Lenovo v530 PC and the PC specifications are almost same as yours.

Its intel i5 8400, but your EFI isn't working for this PC and it gets stuck during boot.

Can you please help me troubleshoot and fix this? And I can paypal you 5 to 10 usd for your efforts sir. Thanks.

**Comment by ThrRip** [comment]
First of all, sorry for letting you wait for about two weeks.

Just add `-v debug=0x100` to your `boot-args` and see where it gets stuck on.

Anyways, this might be the last issue of this repo because I've already switched to a new PC.
