### ISSUE TITLE
CPU Compatibility Issue

### ISSUE THREAD

**Issue by Installer0001** [ThrRip/OpenCore-EFI-Lenovo-B360-i5-8400#3]
Hi I have a Lenovo v530 PC and the PC specifications are almost same as yours.

Its intel i5 8400, but your EFI isn't working for this PC and it gets stuck during boot.

Can you please help me troubleshoot and fix this?

**Comment by ThrRip** [comment]
Just add `-v debug=0x100` to your `boot-args` so you can see where it gets stuck on.

**Comment by Installer0001** [comment]
For those who need this EFI, attached is the 0.7.1 EFI that worked for me until Big Sur. I will update further 0.7.5 shortly that will work for Monterey.

[Lenovo_v530_0.7.1.zip](https://github.com/ThrRip/OpenCore-EFI-Lenovo-B360-i5-8400/files/7466238/Lenovo_v530_0.7.1.zip)

**Comment by ThrRip** [comment]
Thanks for that.
